# Generated by Django 5.1.4 on 2024-12-19 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Wing', 'Wing'), ('Fuselage', 'Fuselage'), ('Tail', 'Tail'), ('Avionics', 'Avionics')], max_length=50)),
                ('aircraft', models.CharField(max_length=50)),
                ('is_assembled', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rental.team')),
            ],
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avionics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avionics', to='rental.part')),
                ('fuselage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuselage', to='rental.part')),
                ('tail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tail', to='rental.part')),
                ('wing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wing', to='rental.part')),
            ],
        ),
    ]
