# Generated by Django 5.1.4 on 2024-12-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_part_aircraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='name',
            field=models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('AKINCI', 'AKINCI'), ('KIZILELMA', 'KIZILELMA')], max_length=100),
        ),
    ]
