# Generated by Django 5.1.4 on 2024-12-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_alter_aircraft_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='aircraft',
            field=models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('AKINCI', 'AKINCI'), ('KIZILELMA', 'KIZILELMA')]),
        ),
        migrations.AlterField(
            model_name='part',
            name='type',
            field=models.CharField(choices=[('Wing', 'Wing'), ('Fuselage', 'Fuselage'), ('Tail', 'Tail'), ('Avionics', 'Avionics')]),
        ),
    ]
