# Generated by Django 5.1.4 on 2024-12-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_remove_personnel_name_personnel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='responsible',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
